### ISSUE TITLE
No support for JUnit XML Format?

### ISSUE THREAD

**Issue by jasonmeverett** [google/googletest#3165]
Trying to activate some features in a GitLab CI/CD pipeline. Documentation on the website shows that Google Test is compatible with the "xml" report type, however GitLab doesn't seem to recognize this output properly.

Has anyone had any success (any version, at any time in the past) with incorporating Google Test w/ GitLab CI/CD? I've come across quite a few forum threads and none provide a good solution.

Thanks in advance!

**Comment by Fabian-programmer** [comment]
I've created following snippet and it works fine for me:

```yaml
unit-test:
  stage: test
  script:
    - cd build/test
    - ./Tests --gtest_output=xml
  artifacts:
    reports:
      junit: build/test/test_detail.xml
```
