### ISSUE TITLE
[Bug]: There are syntax errors in 10-feature_request.yml

### ISSUE THREAD

**Issue by horiyu** [google/googletest#4166]
### Describe the issue

I am trying to submit a feature request, but I only see options for Bug Reports and Security Reports. I suspect there may be a syntax error in 10-feature_request.yml, specifically on lines 13, 20, and 27 where a single space appears to be missing.
I apologize if this issue has already been reported🙇‍♂️

**before the change:**
```
name: Feature request
description: Propose a new feature.
title: "[FR]: Please title this feature request"
labels: "enhancement"
body:
  - type: textarea
    id: version
    attributes:
      label: Does the feature exist in the most recent commit?
      description: We recommend using the latest commit from GitHub in your projects.
    validations:
      required: true
 - type: textarea
    id: why
    attributes:
      label: Why do we need this feature?
      description: Ideally, explain why a combination of existing features cannot be used instead.
    validations:
      required: true
 - type: textarea
    id: proposal
    attributes:
      label: Describe the proposal.
      description: Include a detailed description of the feature, with usage examples.
    validations:
      required: true
 - type: textarea
    id: platform
    attributes:
      label: Is the feature specific to an operating system, compiler, or build system version?
      description: If it is, please specify which versions.
    validations:
      required: true
```

**after the change**
```
name: Feature request
description: Propose a new feature.
title: "[FR]: Please title this feature request"
labels: "enhancement"
body:
  - type: textarea
    id: version
    attributes:
      label: Does the feature exist in the most recent commit?
      description: We recommend using the latest commit from GitHub in your projects.
    validations:
      required: true
  - type: textarea #fixed
    id: why
    attributes:
      label: Why do we need this feature?
      description: Ideally, explain why a combination of existing features cannot be used instead.
    validations:
      required: true
  - type: textarea #fixed
    id: proposal
    attributes:
      label: Describe the proposal.
      description: Include a detailed description of the feature, with usage examples.
    validations:
      required: true
  - type: textarea #fixed
    id: platform
    attributes:
      label: Is the feature specific to an operating system, compiler, or build system version?
      description: If it is, please specify which versions.
    validations:
      required: true
```

### Steps to reproduce the problem

GitHub > googletest > Issues > [New issue](https://github.com/google/googletest/issues/new/choose)

<img width="1170" alt="image" src="https://user-images.githubusercontent.com/80097719/220604403-ae23abfd-71aa-4716-b8ec-9b96a422013e.png">

### What version of GoogleTest are you using?

N/A

### What operating system and version are you using?

macOS Ventura

### What compiler and version are you using?

N/A

### What build system are you using?

N/A

### Additional context

It is possible that there are others who are having the same problem.

[Discussion #3425](https://github.com/google/googletest/discussions/3425)
[Discussion #4160](https://github.com/google/googletest/discussions/4160)
